title: Top Coders Mexico
theme: minima
tagline: "Mexican developers ranking based on github stats"
description: "Mexican developers ranking based on github stats"
url: "https://joelibaceta.github.io/top-coders-mexico/"
author: "Joel Ibaceta"
locale: "es-MX"
plugins:
  - jekyll-seo-tag
